### Register
POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "razzaq",
  "password": "rahasia",
  "name": "Abdul Razzaq"
}

### Login
POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "razzaq",
  "password": "rahasia"
}

### Get User
GET http://localhost:8080/api/users/current
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Update User
PATCH http://localhost:8080/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "name": "Abdul Razzaq Baru"
}

### Create Contact
POST http://localhost:8080/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "firstName": "Joko",
  "lastName": "Samudro",
  "email": "joko@example.com",
  "phone": "1412323123"
}

### Failed Create Contact
POST http://localhost:8080/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "firstName": "",
  "lastName": "Dito",
  "email": "dito@example.com",
  "phone": "123123123"
}

### Search Contact
GET http://localhost:8080/api/contacts
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Query Search Contact
GET http://localhost:8080/api/contacts
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Get Contact
GET http://localhost:8080/api/contacts/03098351-75e4-4805-ab8e-1e792ee87e01
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Update Contact
PATCH http://localhost:8080/api/contacts/03098351-75e4-4805-ab8e-1e792ee87e01
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "firstName": "Budi",
  "phone": "542312342"
}

### Remove Contact
DELETE http://localhost:8080/api/contacts/03098351-75e4-4805-ab8e-1e792ee87e01
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Create Address
POST http://localhost:8080/api/contacts/60716d75-db9e-48c7-abbb-40a2b208b43f/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "street": "Jalan",
  "city": "Surabaya",
  "province": "JATIM",
  "country": "Indonesia",
  "postalCode": "4123"
}

### List Address
GET http://localhost:8080/api/contacts/60716d75-db9e-48c7-abbb-40a2b208b43f/addresses
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Update Address
PUT http://localhost:8080/api/contacts/60716d75-db9e-48c7-abbb-40a2b208b43f/addresses/ad00b995-9d15-45aa-88c2-77093e5c8921
Accept: application/json
Content-Type: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

{
  "street": "Jalan Baru",
  "city": "Surabaya",
  "province": "JATIM",
  "country": "Indonesia",
  "postalCode": "4123"
}

### Remove Address
DELETE http://localhost:8080/api/contacts/60716d75-db9e-48c7-abbb-40a2b208b43f/addresses/ad00b995-9d15-45aa-88c2-77093e5c8921
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d

### Logout User
DELETE http://localhost:8080/api/auth/logout
Accept: application/json
X-API-TOKEN: f5313053-53ef-4899-8f54-a16b9ae2de6d